name: front ci

on:
  push:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - "packages/backend-common/**"
      - "packages/node-api/**"
      - "packages/scan/**"
      - "packages/server/**"
  pull_request:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - "packages/backend-common/**"
      - "packages/node-api/**"
      - "packages/scan/**"
      - "packages/server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: install
        run: yarn

      - name: lint
        run: yarn workspace @paid-qa/site lint

      - name: build
        run: yarn workspace @paid-qa/site build
